name: CI — build + SAST + SCA

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Xmx2g
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Cache dependency-check DB
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/DependencyCheck
            ./.dependency-check-data
          key: ${{ runner.os }}-dependency-check-${{ hashFiles('**/pom.xml') }}

      - name: Build, run tests and static analyzers (maven verify)
        run: mvn -B -V -DskipTests=false verify

      - name: Upload SpotBugs report (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-report
          path: target/spotbugsXml.xml

      - name: Annotate SpotBugs results
        if: always()
        uses: jwgmeligmeyling/spotbugs-github-action@v1
        with:
          report_paths: target/spotbugsXml.xml

      - name: Upload OWASP Dependency-Check reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: |
            target/dependency-check-report.html
            target/dependency-check-report.json
            target/dependency-check-report.xml
